### ISSUE TITLE
nothing works. php errors.

### ISSUE THREAD

**Issue by XKMR** [jxroot/adbwebkit#5]
ERROR<br />
<b>Warning</b>:  Undefined variable $verb in <b>D:\Cfiles\adbwebkit-master\adbwebkit\process\request.php</b> on line <b>112</b><br />
 or similar. 
no errors in php's command line.
and when I open the web page I see the "do you allow ADB? " an I always say "allow"

error (similar looking error for any function):

![image](https://user-images.githubusercontent.com/58393719/160626627-a18f925a-8e33-4275-afd0-2228ac01d970.png)

**Comment by XKMR** [comment]
ای بابا دا خو اگه ایرانی هستی چرا از اول نگفتی

**Comment by jxroot** [comment]
سلام جیگر جوابتو دادم  Sent from Mail for Windows From: kamyarSent: Tuesday, March 29, 2022 6:26 PMTo: jxroot/adbwebkitCc: SubscribedSubject: Re: [jxroot/adbwebkit] nothing works. php errors. (Issue #5) ای بابا دا خو اگه ایرانی هستی چرا از اول نگفتی—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
